### ISSUE TITLE
Problem with keyboard on Raspberri Pi 400

### ISSUE THREAD

**Issue by wyan** [BlokasLabs/blokas-os-gen#2]
I have installed the Patchbox image on an SD card, then boot it on a RPi 400. At first it resizes the filesystem and reboots, then it seems to start in text mode fine, but once the login prompt appears, there's no keyboard input. On reboot, it sometimes boots only when I connect the monitor to the first HDMI port, sometimes when I connect it to the second port, but seems to behave quite erratically overall.

I am using the official RPi PSU, so lack of power shouldn't be an issue. Plugging an external USB keyboard seems to do nothing either.

**Comment by gtrainavicius** [comment]
What is the image version that you have installed? 2020.03.14 or 2020-11-23?

**Comment by wyan** [comment]
Ah, it turns out I was running on 2020.03.14, sorry 🤦‍♀️
Reflashed with 2020.11.23 and followed https://community.blokas.io/t/patchbox-gets-corrupted-on-first-boot-raspberry-pi-4-8gb/1867/16 and now it is working.
Thank you!
